/**
 * Antigravity / Gemini adapter: emit `GEMINI.md` + `.agent/skills/`. Rollout order #4.
 *
 * Antigravity (Gemini CLI lineage) reads GEMINI.md / AGENTS.md and supports
 * `.agent/skills/`. Here we project the canon into GEMINI.md and the harness's
 * durable skills registry (the `skills` collection) into `.agent/skills/<name>/SKILL.md`
 * via the shared markdown renderer (sync/export.ts).
 *
 * NOTE: this is the EXPORT adapter (canon -> GEMINI.md). It is distinct from the
 * future `providers/antigravity` HostAdapter (Antigravity as IDE host/orchestrator).
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { loadDefinitions, renderDefinitionMarkdown, sanitizeFileName, writeIfChanged } from "../sync/export.js";
import { type Canon, type ToolAdapter, renderRules } from "./base.js";

export class AntigravityAdapter implements ToolAdapter {
  readonly name = "antigravity";

  async export(canon: Canon, repoRoot: string): Promise<string[]> {
    const out = join(repoRoot, "GEMINI.md");
    const content =
      "<!-- generated by AITL-Harness from AGENTS.md — do not edit -->\n\n" +
      "# Project conventions\n\n" +
      `${renderRules(canon)}\n`;
    await fs.writeFile(out, content, "utf-8");
    const written = [out];
    // Skills registry → Antigravity's native `.agent/skills/<name>/SKILL.md`.
    for (const skill of await loadDefinitions("skill", canon.project)) {
      const path = join(repoRoot, ".agent", "skills", sanitizeFileName(skill.name), "SKILL.md");
      await writeIfChanged(path, renderDefinitionMarkdown(skill));
      written.push(path);
    }
    return written;
  }
}
