/**
 * Antigravity / Gemini adapter: emit `GEMINI.md`. Rollout order #4.
 *
 * Antigravity (Gemini CLI lineage) reads GEMINI.md / AGENTS.md and supports
 * `.agent/skills/`. Here we project the canon into GEMINI.md; skills export is a TODO.
 *
 * NOTE: this is the EXPORT adapter (canon -> GEMINI.md). It is distinct from the
 * future `providers/antigravity` HostAdapter (Antigravity as IDE host/orchestrator).
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { type Canon, type ToolAdapter, renderRules } from "./base.js";

export class AntigravityAdapter implements ToolAdapter {
  readonly name = "antigravity";

  async export(canon: Canon, repoRoot: string): Promise<string[]> {
    const out = join(repoRoot, "GEMINI.md");
    const content =
      "<!-- generated by AITL-Harness from AGENTS.md — do not edit -->\n\n" +
      "# Project conventions\n\n" +
      `${renderRules(canon)}\n`;
    await fs.writeFile(out, content, "utf-8");
    // TODO(phase 9): export skills into `.agent/skills/<name>/` when the harness
    // gains a skills registry.
    return [out];
  }
}
