/** GitHub Copilot adapter: emit `.github/copilot-instructions.md`. Rollout order #3. */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { type Canon, type ToolAdapter, renderRules } from "./base.js";

export class CopilotAdapter implements ToolAdapter {
  readonly name = "copilot";

  async export(canon: Canon, repoRoot: string): Promise<string[]> {
    const gh = join(repoRoot, ".github");
    await fs.mkdir(gh, { recursive: true });
    const out = join(gh, "copilot-instructions.md");
    const content =
      "<!-- generated by AITL-Harness from AGENTS.md — do not edit -->\n\n" +
      "# Project conventions\n\n" +
      `${renderRules(canon)}\n`;
    await fs.writeFile(out, content, "utf-8");
    return [out];
  }
}
