/**
 * Kiro adapter: emit `.kiro/steering/*.md`. Rollout order #5.
 *
 * Kiro's steering files are *always loaded* (cannot be accidentally omitted) — the
 * closest existing analogue to AITL's durable-conventions goal. We write one steering
 * file from conventions and one from decisions (ADRs).
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { type Canon, type ToolAdapter, renderRules } from "./base.js";

export class KiroAdapter implements ToolAdapter {
  readonly name = "kiro";

  async export(canon: Canon, repoRoot: string): Promise<string[]> {
    const steering = join(repoRoot, ".kiro", "steering");
    await fs.mkdir(steering, { recursive: true });
    const written: string[] = [];

    const conv = join(steering, "conventions.md");
    await fs.writeFile(conv, `# Conventions (generated by AITL-Harness)\n\n${renderRules(canon)}\n`, "utf-8");
    written.push(conv);

    if (canon.decisions.length) {
      const dec = join(steering, "decisions.md");
      const lines = ["# Decisions (ADRs, generated by AITL-Harness)", ""];
      for (const d of canon.decisions) {
        lines.push(`## ADR-${String(d.id)}: ${String(d.title)}`);
        lines.push(String(d.decision ?? ""));
        lines.push("");
      }
      await fs.writeFile(dec, lines.join("\n"), "utf-8");
      written.push(dec);
    }
    return written;
  }
}
