/**
 * Trae adapter: emit Trae project rules. Rollout order #6.
 *
 * Trae reads project rules / AGENTS.md. We write `.trae/rules/project_rules.md` from
 * the canon (and Trae also natively reads the repo's AGENTS.md as a fallback).
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { type Canon, type ToolAdapter, renderRules } from "./base.js";

export class TraeAdapter implements ToolAdapter {
  readonly name = "trae";

  async export(canon: Canon, repoRoot: string): Promise<string[]> {
    const rulesDir = join(repoRoot, ".trae", "rules");
    await fs.mkdir(rulesDir, { recursive: true });
    const out = join(rulesDir, "project_rules.md");
    await fs.writeFile(out, `# Project rules (generated by AITL-Harness)\n\n${renderRules(canon)}\n`, "utf-8");
    return [out];
  }
}
