/**
 * `aitl init agent` — write an AGENTS.md operating contract.
 *
 * The generated guide is a durable reminder that ANY agent working in the repo must
 * consult the AITL MCP (durable memory + decisions) BEFORE every non-trivial decision,
 * and persist what it learns/decides AFTER. This turns the MCP into the source of truth
 * instead of probabilistic in-context memory.
 */

import { promises as fs } from "node:fs";
import { createInterface } from "node:readline/promises";

export interface AgentGuideOpts {
  out: string;
  project: string;
  mcp: string;
  interactive?: boolean;
  force?: boolean;
}

function renderGuide(project: string, mcp: string): string {
  return `# Agent operating contract (AITL)

> Generated by \`aitl init agent\`. This file is a **durable instruction** for any AI
> agent (Claude Code, Cursor, etc.) working in this repository. Treat the AITL MCP
> server **\`${mcp}\`** as the source of truth — not your in-context memory.

## Project scope

Use the project **\`${project}\`** for all MCP calls below.

## Before EVERY non-trivial decision — CONSULT THE MCP

Do not decide from memory. First query durable state via the \`${mcp}\` MCP server:

1. \`search_memory\` — semantic recall over prior memory/notes for this project.
2. \`list_decisions\` — the Architecture Decision Records already taken (don't contradict
   or re-litigate an accepted ADR; if you must, supersede it explicitly).
3. \`get_repomap\` — when the decision touches code structure.

If the MCP and your assumptions disagree, **the MCP wins** — or surface the conflict.

## After deciding / learning — PERSIST IT

1. \`record_decision\` — record any architectural decision as an ADR (Context / Decision /
   Consequences). Decisions that aren't written down don't exist.
2. \`write_memory\` — capture durable facts, preferences, and gotchas as structured memory
   (\`type\`: user | feedback | project | reference), keyed by a stable slug.
3. Record the prompt/instruction that drove the work (prompt history) so the session is
   reconstructable.

## Rules of thumb

- **Recall before reasoning.** A 1-second \`search_memory\` beats re-deriving context.
- **One decision → one ADR.** Keep them small and append-only.
- **Don't duplicate.** Update an existing memory/decision instead of creating a near-copy.
- **Scope everything** to project \`${project}\`.

## Quick reference (CLI equivalents)

\`\`\`bash
aitl search "<query>" --project ${project}          # semantic recall
aitl adr-sync --dir docs/adr --project ${project}    # mirror ADRs into Mongo
aitl prompt list --project ${project}                # prompt history
aitl ui --project ${project}                          # browse/edit memories in the web UI
\`\`\`
`;
}

export async function writeAgentGuide(opts: AgentGuideOpts): Promise<string> {
  let { out, project, mcp } = opts;

  if (opts.interactive) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    try {
      out = (await rl.question(`Output file [${out}]: `)).trim() || out;
      project = (await rl.question(`Project scope [${project}]: `)).trim() || project;
      mcp = (await rl.question(`MCP server name [${mcp}]: `)).trim() || mcp;
    } finally {
      rl.close();
    }
  }

  // Guard against clobbering an existing AGENTS.md (symmetry with `init claude`).
  if (!opts.force) {
    try {
      await fs.access(out);
      throw new Error(`${out} already exists. Re-run with --force to overwrite.`);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
  }

  await fs.writeFile(out, renderGuide(project, mcp), "utf-8");
  return out;
}
